### ISSUE TITLE
关于规则问题

### ISSUE THREAD

**Issue by ghost** [zhiyuan1i/adblock_list#1]
Hi,
@uniartisan 
关于basic文档可以请你调整一下吗？

这条请你移除
`||ettoday.net/events/ad-tab/`

这些可以请你添加吗?
```
||ettoday.net/events/
||doubleclick.net^
||trvdp.com^
||criteo.net^
```

thanks!

**Comment by e-tw** [comment]
> 
> 
> Hi,
> @uniartisan
> 关于basic文档可以请你调整一下吗？
> 
> 这条请你移除
> `||ettoday.net/events/ad-tab/`
> 
> 这些可以请你添加吗?
> 
> ```
> ||ettoday.net/events/
> ||doubleclick.net^
> ||trvdp.com^
> ||criteo.net^
> ```
> 
> thanks!

**Comment by zhiyuan1i** [comment]
请详细描述此条规则和下述规则所影响的具体范围。
如：此规则影响了 xxxx 页面某组件的正常显示，属于误报。或此规则存在一下问题：xxx
下面的规则也请你给出具体的页面，便于我排查。

> doubleclick.net
此域名我看到已经存在过滤规则，暂时不予考虑。
> criteo.net
这是个营销公司的域名，这是隐私搜集域名吗？有没有更确切的描述。

adblock_list是一个定位于保证广告过滤效率的前提下减少误杀的项目，请您理解详细描述的意义。
如果是隐私收集域名我会将其专用于数据收集的子域名加入隐私保护列表。
