### ISSUE TITLE
建议把规则放进coding，gitee链接1m以上需登录！

### ISSUE THREAD

**Issue by hacamer** [zhiyuan1i/adblock_list#3]
建议把规则放进coding

**Comment by zhiyuan1i** [comment]
Hello @hacamer, thank you for your interest in our work! It’s people like you who make our work better!

**Comment by zhiyuan1i** [comment]
您好，可以考虑 jsDelivr 中国大陆地区仍可以访问。

**Comment by hacamer** [comment]
目前使用iQDNS的github镜像，感觉不错，
```https://raw.iqiq.io/uniartisan/adblock_list/master/adblock_plus.txt```

**Comment by zhiyuan1i** [comment]
Commit https://github.com/uniartisan/adblock_list/commit/ae4dd2c52f8a472dd3a7a4679488429fca12bdc3
