### ISSUE TITLE
adblock提示筛选器列表无效

### ISSUE THREAD

**Issue by NStudio-Service** [zhiyuan1i/adblock_list#4]
![image](https://user-images.githubusercontent.com/62399403/159610696-d9940302-b656-49fe-9926-4227cf1c09a1.png)
如图，绝对不是网络问题，直接访问是可以打开的。

**Comment by zhiyuan1i** [comment]
Hello @NStudio-Service, thank you for your interest in our work! It’s people like you who make our work better!

**Comment by zhiyuan1i** [comment]
可以提供更多细节吗？ 我现在使用的是 adguard

**Comment by NStudio-Service** [comment]
> 可以提供更多细节吗？ 我现在使用的是 adguard

问题已经找到了，我现在用的这个adblock是只认头为[Adblock Plus 2.0]的规则列表。

**Comment by NStudio-Service** [comment]
> 可以提供更多细节吗？ 我现在使用的是 adguard

现在我是自己fork了一个仓库，改掉py脚本中的文件头，然后复制了一份action每天自动生成来解决这个问题。
