### ISSUE TITLE
老大，救命啊

### ISSUE THREAD

**Issue by V2RaySSR** [zhiyuan1i/adblock_list#5]
https://github.com/uniartisan/adblock_list/blob/dfbe88bd901dbe339bd85101f054fa6faf8331f7/adblock.txt#L10865
老大，您好，我是站长也是一个YouTube，这个是我的博客中的跳转链接，当然，您这边是为了客户的体验。但是您可以真实的到网站去看看，除了Google Adsense的广告，我这边就没有任何的影响客户体验的广告。goii.cc，这个短链接，只是我YouTube视频的时候，为客户介绍产品的时候，为了方便客户记忆（因为目前很多产品网站都不停的变换域名），而搭建的一个私人的网站，这个 goii.cc 并没有对任何人开放缩短业务！然而，在博客中全部禁用goii.cc的跳转，这个是致命的，goii 并没有任何的广告性质，请您务必去网站看一下！若是不行，也请您回复一下！我冒昧的问一句，我还能用其他的什么办法来恢复！因为这个是致命的。。。

**Comment by zhiyuan1i** [comment]
Hello @V2RaySSR, thank you for your interest in our work! It’s people like you who make our work better!

**Comment by V2RaySSR** [comment]
真心的只是产品页面的跳转！麻烦您在百忙中，去核实一下。

**Comment by V2RaySSR** [comment]
这个是有人盯着我吗？

**Comment by zhiyuan1i** [comment]
已经核实是短链接跳转，会加白。

**Comment by zhiyuan1i** [comment]
https://github.com/uniartisan/adblock_list/commit/dc31069c28bdd34d6e42a760d4773c19cb5758e4

这个 commit 修复了您的问题。
