### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by V2RaySSR** [zhiyuan1i/adblock_list#6]
域名：goii.cc
发生时间：2022年 6月30日
使用的列表： (adblock.txt)
使用的列表版本： (2022-06-30 11:08)
浏览器及广告过滤插件：
问题描述：v2rayssr.com##a[href*="goii.cc"] 
老大，您好，我是站长也是一个YouTube，这个是我的博客中的跳转链接，当然，您这边是为了客户的体验。但是您可以真实的到网站去看看，除了Google Adsense的广告，我这边就没有任何的影响客户体验的广告。goii.cc，这个短链接，只是我YouTube视频的时候，为客户介绍产品的时候，为了方便客户记忆（因为目前很多产品网站都不停的变换域名），而搭建的一个私人的网站，这个 goii.cc 并没有对任何人开放缩短业务！然而，在博客中全部禁用goii.cc的跳转，这个是致命的，goii 并没有任何的广告性质，请您务必去网站看一下！若是不行，也请您回复一下！我冒昧的问一句，我还能用其他的什么办法来恢复！因为这个是致命的。。。我觉得，这是有人故意的。。。

**Comment by zhiyuan1i** [comment]
https://github.com/uniartisan/adblock_list/commit/dc31069c28bdd34d6e42a760d4773c19cb5758e4

这个 commit 修复了您的问题。

**Comment by zhiyuan1i** [comment]
可以看看上游是哪个具体的规则造成，向维护者提供相关信息修正。
