### ISSUE TITLE
[新增广告拦截]

### ISSUE THREAD

**Issue by qrer1** [zhiyuan1i/adblock_list#7]
域名：https://www.iqiyi.com/a_2fkj4571u8d.html?vfrm=pcw_home&vfrmblk=B&vfrmrst=fcs_0_t14
发生时间：  2022年 7 月3 日
使用的列表： adblock-basic
使用的列表版本： 202207030306
浏览器及广告过滤插件：uBlock Origin 1.43.0 Chrome 103.0.5060.66
问题描述：

注意： 如果您使用的是 adblock_basic 列表，您应该先尝试使用 adblock_plus，adblock_basic 是主要面向于中文（尤其是指中国境内）网站而制作的过滤列表。

**Comment by zhiyuan1i** [comment]
Hello @qrer1, thank you for your interest in our work! It’s people like you who make our work better!

**Comment by zhiyuan1i** [comment]
使用  adblock_plus 没有复现广告问题，basic 只作为快速版本，无法体会到最佳拦截效果。若您使用现代硬件，应该更换列表。
https://raw.githubusercontent.com/uniartisan/adblock_list/master/adblock_plus.txt
