### ISSUE TITLE
Does it work with Adguard home?

### ISSUE THREAD

**Issue by xenstar** [zhiyuan1i/adblock_list#8]
Can the list be used with Adguard home? Or we need to use it with ublock origin?

**Comment by zhiyuan1i** [comment]
Hello @xenstar, thank you for your interest in our work! It’s people like you who make our work better!

**Comment by zhiyuan1i** [comment]
Sure! I am using it with ublock origin, and I have tested it with Adguard home. However, this may not be the best choice for Adgurad home because it is not designed for hosts.
